# Generated by Django 6.0.6 on 2026-07-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='link',
        ),
    ]
